name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/group-33345.png
    - assets/page-1/images/group-33345-Eyc.png
    - assets/page-1/images/left-side.png
    - assets/page-1/images/gridicons-dropdown.png
    - assets/page-1/images/frame.png
    - assets/page-1/images/uil-transaction.png
    - assets/page-1/images/group-33345-enJ.png
    - assets/page-1/images/gridicons-dropdown-Tt2.png
    - assets/page-1/images/uil-transaction-opi.png
    - assets/page-1/images/material-symbols-add-circle-outline-rounded.png
    - assets/page-1/images/gridicons-dropdown-n86.png
    - assets/page-1/images/gridicons-dropdown-byG.png
    - assets/page-1/images/frame-atN.png
    - assets/page-1/images/material-symbols-add-circle-outline-rounded-Kw4.png
    - assets/page-1/images/lucide-layout-dashboard.png
    - assets/page-1/images/twemoji-family-man-woman-boy.png
    - assets/page-1/images/gridicons-dropdown-gaJ.png
    - assets/page-1/images/group-33345-dCa.png
    - assets/page-1/images/left-side-T1p.png
    - assets/page-1/images/fi-rr-user.png
    - assets/page-1/images/group-33345-Fy8.png
    - assets/page-1/images/eva-arrow-back-outline.png
    - assets/page-1/images/group-33345-5x2.png
    - assets/page-1/images/group-33345-JVk.png
    - assets/page-1/images/group-33345-bmQ.png
    - assets/page-1/images/gridicons-dropdown-vBY.png
    - assets/page-1/images/group-33345-vaA.png
    - assets/page-1/images/eva-arrow-back-outline-MRp.png
    - assets/page-1/images/gridicons-dropdown-crr.png
    - assets/page-1/images/group-33345-sxS.png
    - assets/page-1/images/gridicons-dropdown-C4E.png
    - assets/page-1/images/group-33345-pWJ.png
    - assets/page-1/images/ic-baseline-upload-file.png
    - assets/page-1/images/group-33345-kwQ.png
    - assets/page-1/images/frame-rXp.png
    - assets/page-1/images/group-33345-GxE.png
    - assets/page-1/images/group-33345-QXx.png
    - assets/page-1/images/left-side-TNN.png
    - assets/page-1/images/group-33345-Ser.png
    - assets/page-1/images/gridicons-dropdown-jmG.png
    - assets/page-1/images/ic-baseline-upload-file-xKp.png
    - assets/page-1/images/group-33345-hMg.png
    - assets/page-1/images/group-33345-26A.png
    - assets/page-1/images/group-33345-BD8.png
    - assets/page-1/images/group-33345-y74.png
    - assets/page-1/images/left-side-JAa.png
    - assets/page-1/images/ic-baseline-upload-file-H18.png
    - assets/page-1/images/group-33345-d58.png
    - assets/page-1/images/left-side-JqU.png
    - assets/page-1/images/eva-arrow-back-outline-CeS.png
    - assets/page-1/images/group-33345-sxA.png
    - assets/page-1/images/group-33345-nkv.png
    - assets/page-1/images/group-33345-dkr.png
    - assets/page-1/images/eva-arrow-back-outline-eBY.png
    - assets/page-1/images/group-33345-v3p.png
    - assets/page-1/images/frame-6Si.png
    - assets/page-1/images/ep-success-filled.png
    - assets/page-1/images/material-symbols-add-circle-outline-rounded-9ve.png
    - assets/page-1/images/gridicons-dropdown-8SA.png
    - assets/page-1/images/gridicons-dropdown-Wk6.png
    - assets/page-1/images/group-33345-R7U.png
    - assets/page-1/images/group-33345-1F4.png
    - assets/page-1/images/group-33345-678.png
    - assets/page-1/images/group-33345-BGz.png
    - assets/page-1/images/bi-zoom-in.png
    - assets/page-1/images/frame-p4N.png
    - assets/page-1/images/gridicons-dropdown-YWS.png
    - assets/page-1/images/eva-arrow-back-outline-RdQ.png
    - assets/page-1/images/group-33345-VeW.png
    - assets/page-1/images/ep-success-filled-Q8W.png
    - assets/page-1/images/left-side-1xr.png
    - assets/page-1/images/left-side-shx.png
    - assets/page-1/images/frame-v1C.png
    - assets/page-1/images/group-33345-XFc.png
    - assets/page-1/images/gridicons-dropdown-654.png
    - assets/page-1/images/group-33345-aYW.png
    - assets/page-1/images/group-33345-HgS.png
    - assets/page-1/images/gridicons-dropdown-KwC.png
    - assets/page-1/images/group-33345-XC2.png
    - assets/page-1/images/frame-rTp.png
    - assets/page-1/images/group-33345-cx6.png
    - assets/page-1/images/ic-baseline-upload-file-jkS.png
    - assets/page-1/images/group-33345-FAN.png
    - assets/page-1/images/group-33345-uJ6.png
    - assets/page-1/images/group-33345-6UN.png
    - assets/page-1/images/eva-arrow-back-outline-H4J.png
    - assets/page-1/images/group-33345-UnJ-ewg.png
    - assets/page-1/images/left-side-WR4.png
    - assets/page-1/images/c0c0dhkukaa1jqq-1-bg.png
    - assets/page-1/images/auto-group-hgaw.png
    - assets/page-1/images/eva-arrow-back-outline-xDc.png
    - assets/page-1/images/ic-baseline-upload-file-1Qr.png
    - assets/page-1/images/group-33345-kxW.png
    - assets/page-1/images/c0c0dhkukaa1jqq-1-bg-nRC.png
    - assets/page-1/images/group-33345-tSS.png
    - assets/page-1/images/ic-baseline-upload-file-XnN.png
    - assets/page-1/images/group-33345-yhG.png
    - assets/page-1/images/gridicons-dropdown-zXp.png
    - assets/page-1/images/group-33345-EWJ.png
    - assets/page-1/images/frame-CT8.png
    - assets/page-1/images/group-33345-dYS.png
    - assets/page-1/images/material-symbols-add-circle-outline-rounded-BK4.png
    - assets/page-1/images/ic-baseline-upload-file-wJE.png
    - assets/page-1/images/group-33345-8tW.png
    - assets/page-1/images/group-33345-hgi.png
    - assets/page-1/images/left-side-422.png
    - assets/page-1/images/gridicons-dropdown-vZ4.png
    - assets/page-1/images/group-33345-H8i.png
    - assets/page-1/images/frame-35G.png
    - assets/page-1/images/gridicons-dropdown-A4e.png
    - assets/page-1/images/frame-KTL.png
    - assets/page-1/images/left-side-H9G.png
    - assets/page-1/images/frame-3u8.png
    - assets/page-1/images/group-33345-koY.png
    - assets/page-1/images/group-33345-XJW.png
    - assets/page-1/images/group-33345-pYW.png
    - assets/page-1/images/group-33345-vMt.png
    - assets/page-1/images/group-33345-Tci.png
    - assets/page-1/images/ic-baseline-upload-file-pCN.png
    - assets/page-1/images/bi-zoom-in-Yna.png
    - assets/page-1/images/group-33345-nwp.png
    - assets/page-1/images/eva-arrow-back-outline-iH4.png
    - assets/page-1/images/left-side-jxr.png
    - assets/page-1/images/group-33345-xmc.png
    - assets/page-1/images/mdi-bank-transfer.png
    - assets/page-1/images/gridicons-dropdown-2Vt.png
    - assets/page-1/images/ic-baseline-upload-file-8BY.png
    - assets/page-1/images/group-33345-UnJ.png
    - assets/page-1/images/frame-5Mg.png
    - assets/page-1/images/group-33345-YPg.png
    - assets/page-1/images/group-33345-MzW.png
    - assets/page-1/images/group-33345-j5x.png
    - assets/page-1/images/left-side-tjY.png
    - assets/page-1/images/eva-arrow-back-outline-3sL.png
    - assets/page-1/images/ic-baseline-upload-file-1JN.png
    - assets/page-1/images/ic-baseline-upload-file-mpr.png
    - assets/page-1/images/group-33345-anJ.png
    - assets/page-1/images/group-33345-nKx.png
    - assets/page-1/images/group-33345-Y4E.png
    - assets/page-1/images/group-33345-4KQ.png
    - assets/page-1/images/group-33345-tZL.png
    - assets/page-1/images/mdi-bank-transfer-pUE.png
    - assets/page-1/images/uil-process.png
    - assets/page-1/images/group-33345-tdL.png
    - assets/page-1/images/eva-arrow-back-outline-PJN.png
    - assets/page-1/images/bi-zoom-in-sdQ.png
    - assets/page-1/images/frame-Awp.png
    - assets/page-1/images/bi-zoom-in-vJi.png
    - assets/page-1/images/ic-baseline-upload-file-gbG.png
    - assets/page-1/images/frame-AYN.png
    - assets/page-1/images/group-33345-bwk.png
    - assets/page-1/images/bi-zoom-in-dZY.png
    - assets/page-1/images/left-side-uQa.png
    - assets/page-1/images/left-side-ECW.png
    - assets/page-1/images/frame-tHk.png
    - assets/page-1/images/eva-arrow-back-outline-9uY.png
    - assets/page-1/images/group-33345-JLW.png
    - assets/page-1/images/left-side-tBY.png
    - assets/page-1/images/frame-Rta.png
    - assets/page-1/images/group-33345-mxS.png
    - assets/page-1/images/bi-zoom-in-t1U.png
    - assets/page-1/images/eva-arrow-back-outline-Er2.png
    - assets/page-1/images/group-33345-bTc.png
    - assets/page-1/images/ic-baseline-upload-file-2Yv.png
    - assets/page-1/images/group-33345-hf4.png
    - assets/page-1/images/frame-iaA.png
    - assets/page-1/images/group-33345-eii.png
    - assets/page-1/images/ic-baseline-upload-file-1ZG.png
    - assets/page-1/images/group-33345-BCr.png
    - assets/page-1/images/ic-baseline-upload-file-LbY.png
    - assets/page-1/images/group-33345-MmY.png
    - assets/page-1/images/left-side-W5L.png
    - assets/page-1/images/c0c0dhkukaa1jqq-1-bg-7DQ.png
    - assets/page-1/images/group-33345-cC6.png
    - assets/page-1/images/eva-arrow-back-outline-fw4.png
    - assets/page-1/images/ic-baseline-upload-file-wta.png
    - assets/page-1/images/mdi-bank-transfer-N1U.png
    - assets/page-1/images/group-33345-ib8.png
    - assets/page-1/images/c0c0dhkukaa1jqq-1-bg-bnv.png
    - assets/page-1/images/mdi-bank-transfer-bpr.png
    - assets/page-1/images/group-33345-7oC.png
    - assets/page-1/images/uil-process-1i6.png
    - assets/page-1/images/ic-baseline-upload-file-qne.png
    - assets/page-1/images/ic-baseline-upload-file-4rA.png
    - assets/page-1/images/eva-arrow-back-outline-hiN.png
    - assets/page-1/images/group-33345-geA.png
    - assets/page-1/images/eva-arrow-back-outline-Bxa.png
    - assets/page-1/images/c0c0dhkukaa1jqq-1-bg-kxW.png
    - assets/page-1/images/left-side-aCn.png
    - assets/page-1/images/group-33345-bTc-Amc.png
    - assets/page-1/images/c0c0dhkukaa1jqq-1-bg-FFC.png
    - assets/page-1/images/eva-arrow-back-outline-RyQ.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
